- .gitignore
- app/utils/ApiClient.ts
- app/utils/Environment.ts
Tried setting up environment config via the `.env` files and `process.env.key` formula but it wasn't working. So I put this together instead. I feel its good enough for now.
> Environment config

- app/components/screens/products/FloatingActionButtonMenu.tsx
- app/components/screens/products/Products.tsx
- app/components/screens/products/ProductsSearchCodeHeader.tsx
- app/components/screens/products/State.ts
- app/components/screens/products/VM.ts
- app/components/screens/products/VMMapper.ts
- app/data/product/SearchProducts.ts
Allow a warehouse user to search products by name or SKU
Should allow user to search by name or SKU
Should return a list of products or a single product that matches search
Should allow user to click product to view Product Details screen
> OBKN-44 Allow a warehouse user to search products by name or SKU

- app/components/screens/products/BarCodeSearchHeader.tsx
- app/components/screens/products/Products.tsx
- app/components/screens/products/State.ts
- app/components/screens/products/VM.ts
- app/components/screens/products/VMMapper.ts
- app/data/product/SearchProducts.ts
Searching product globally on product list page.
> OBKN-55 Allow a user to scan a barcode to retrieve details for a product

- app/components/screens/dashboard/Dashboard.tsx
- app/components/screens/dashboard/State.ts
- app/components/screens/orders/Orders.tsx
- app/components/screens/orders/OrdersList.tsx
- app/components/screens/orders/Props.ts
- app/components/screens/orders/State.ts
- app/data/order/GetOrders.ts
- app/data/order/Location.ts
- app/data/order/Order.ts
Allow User to view Order List screen
> OBKN-185 Allow User to view Order List screen

- app/components/screens/order_details/OrderDetails.tsx
- app/components/screens/order_details/OrderDetailsProps.ts
- app/components/screens/order_details/OrderDetailsVMMapper.ts
- app/components/screens/order_details/OrderDetailsVm.ts
- app/components/screens/order_details/State.ts
- app/components/screens/orders/Orders.tsx
- app/components/screens/orders/OrdersList.tsx
- app/components/screens/picklist/PickListProps.ts
- app/components/screens/picklist/PickListVMMapper.ts
- app/components/screens/picklist/PickListVm.ts
- app/components/screens/picklist/PickOrderItem.tsx
- app/components/screens/picklist/State.ts
- app/data/order/Order.ts
- app/data/picklist/BinLocation.ts
- app/data/picklist/GetPickList.ts
- app/data/picklist/Item.ts
- app/data/picklist/Person.ts
- app/data/picklist/PickList.ts
- app/data/picklist/Requisition.ts
OBKN-53 Allow a warehouse user to view details for an outbound order,
Some changes for order list page also.
> OBKN-53 Allow a warehouse user to view details for an outbound order

- src/Main.tsx
- src/apis/packing.ts
- src/data/container/Shipment.ts
- src/redux/actions/packing.ts
- src/redux/sagas/packing.ts
- src/screens/OutboundStockDetails/ContainerDetails.tsx
- src/screens/OutboundStockDetails/ContainerItem.tsx
- src/screens/OutboundStockDetails/index.tsx
- src/screens/OutboundStockDetails/styles.ts
- src/screens/OutboundStockDetails/types.ts
- src/screens/OutboundStockList/index.tsx
OBKN-226 Allow user to view the packing list details of an outbound stock movement
> OBKN-226 Allow user to view the packing list details of an outbound stock movement

- src/apis/orders.ts
- src/redux/actions/orders.ts
- src/screens/OrderDetails/index.tsx
- src/screens/Orders/OrdersList.tsx
- src/screens/Orders/index.tsx
- src/screens/PickList/index.tsx
- src/screens/PickList/styles.ts
- src/screens/Products/BarCodeSearchHeader.tsx
OBKN-231 Improvements to outbound orders search in picking workflow
> OBKN-231 Improvements to outbound orders search in picking workflow 

- src/redux/actions/orders.ts
- src/screens/PickList/index.tsx
- src/screens/PickList/styles.ts
OBKN-277 Improvements to the pick order item screen
> OBKN-277 Improvements to the pick order item screen

- src/Main.tsx
- src/redux/reducers/mainReducer.ts
- src/screens/ProductDetails/index.tsx
- src/screens/Products/BarCodeSearchHeader.tsx
- src/screens/Products/VMMapper.ts
- src/screens/Products/index.tsx
- yarn.lock
OBKN-263 [Core] Improvements to the product listing screen
> OBKN-263 Fix Improvements to the product listing screen

- src/components/Button.tsx
- src/constants.ts
- src/screens/AdjustStock/index.tsx
- src/screens/ProductDetails/index.tsx
- src/screens/ViewAvailableItem/index.tsx
Fix Should handle success / error cases on Adjust Stock screen
> Fix OBKN-284

- android/app/src/main/AndroidManifest.xml
- index.js
- src/Main.tsx
- src/components/AutoComplete/AutoComplete.tsx
- src/hooks/useEventListener.ts
- src/screens/PutawayCandidates/index.tsx
- src/screens/PutawayItem/index.tsx
- src/screens/PutawayItemDetail/types.ts
> Fix OBKN-349

- src/apis/lpn.ts
- src/apis/packing.ts
- src/components/AutoInputInternalLocation/index.tsx
- src/components/AutoInputInternalLocation/types.ts
- src/components/PrintModal/index.tsx
- src/redux/actions/lpn.ts
- src/redux/sagas/lpn.ts
- src/redux/sagas/packing.ts
- src/screens/Dashboard/dashboardData.ts
- src/screens/Lpn/Create.tsx
- src/screens/LpnDetail/Index.tsx
- src/screens/OutboundStockDetails/index.tsx
Add create LPN button to OutboundStockDetails
> OBKN-319 Add create LPN button to OutboundStockDetails

- src/components/InputBox/index.tsx
- src/components/InputBox/types.ts
- src/screens/InternalTransfer/index.tsx
- src/screens/PutawayCandidates/index.tsx
- src/screens/PutawayCandidates/styles.ts
- src/screens/PutawayItem/index.tsx
- yarn.lock
Fixed OBKN-359, OBKN-360 and OBKN-356
> Fixed common PutaWay Detail & Putway Candidate screen issues

- android/app/src/main/AndroidManifest.xml
- src/screens/PutawayItem/styles.ts
Spike: Improve user experience of forms with fields that require keyboard
> Fix OBKN-342

- src/screens/ProductDetails/index.tsx
Fix Inventories with qty=0 visible on mobile app
> Fix OBKN-363

- src/screens/PutawayCandidates/index.tsx
Filter out items from pending putaways from Putaway candidates list
> Filter out items in Putaway candidates list

- src/screens/LpnDetail/Index.tsx
- src/screens/PutawayCandidates/index.tsx
- src/screens/PutawayItem/index.tsx
Bug fixed LPN details screen- import issue 
Fixed import put away item/
Crash issue fixed in Put away candidate
> Crash issue fixed in OBKN323 and put away candidate

- src/components/AutoInputBinLocation/index.tsx
- src/components/AutoInputBinLocation/styles.ts
- src/components/AutoInputBinLocation/types.ts
- src/screens/PutawayItem/index.tsx
Fixed create searchable dropdown for bin locations
> Fixed create searchable dropdown for bin locations

- src/screens/ProductSummary/index.tsx
- src/screens/ProductSummary/styles.tsx
Fix Action menu should be in the same size on all pages
> OBKN-362 Fix Action menu should be in the same size on all pages

- src/screens/ChooseCurrentLocation/index.tsx
- src/screens/InboundOrder/InboundOrderList.tsx
- src/screens/ProductSummary/index.tsx
- src/screens/Products/index.tsx
Fix Inventories with qty=0 visible on mobile app
> OBKN-363 Fix Inventories with QoH = 0 visible on mobile app 

- src/components/InputSpinner.tsx
- src/screens/PutawayItem/index.tsx
- src/screens/PutawayItem/styles.ts
- src/screens/PutawayItemDetail/index.tsx
Fix Unable to putaway to Default bin
> OBKN-376 Fix Unable to putaway to Default bin

- android/app/src/main/AndroidManifest.xml
Temporarily disable ability to rotate to landscape
> OBKN-381 Temporarily disable ability to rotate to landscape

- src/components/AutoInputInternalLocation/index.tsx
- src/screens/LpnDetail/Index.tsx
- src/screens/ShipItemDetails/index.tsx
- src/screens/ShipItemDetails/styles.tsx
- yarn.lock
> OBKN-374 Fix Pack page issues

- src/screens/InboundOrder/InboundOrderList.tsx
- src/screens/InboundOrder/styles.ts
Reverts openboxes/openboxes-mobile#145
> Revert "Bug fix in OBKN 350 The last results on InboundOrderList is cutoff"

- src/components/Radio.tsx
- src/screens/PutawayDetails/index.tsx
- src/screens/PutawayList/index.tsx
Prevent Putaway List from routing to Putaway Detail when only 1 putaway order is listed
> [Fix] OBKN-344

- src/screens/AdjustStock/index.tsx
- src/screens/OrderDetails/index.tsx
- src/screens/PickList/index.tsx
- src/screens/PickList/styles.ts
- src/screens/ShipItemDetails/index.tsx
App freezes on OrderDetails page
> OBKN-308 App freezes on OrderDetails page

- src/screens/AdjustStock/index.tsx
- src/screens/PutawayItemDetail/index.tsx
- src/screens/Transfer/index.tsx
- yarn.lock
Fix Unable to scroll PutawayItemDetail page in landscape
> OBKN-353 Fix Unable to scroll PutawayItemDetail page in landscape

- src/apis/lpn.ts
- src/redux/actions/lpn.ts
- src/redux/sagas/lpn.ts
- src/screens/LpnDetail/Index.tsx
- src/screens/LpnDetail/Types.ts
> OBKN-107  Allow a warehouse user to change the status of a container

- src/screens/Lpn/Create.tsx
- src/screens/PickList/index.tsx
- yarn.lock
Changing Quantity to Pick on PickOrderItem should not change for all items
> OBKN-351 Changing Quantity to Pick on PickOrderItem should not change for all items

- src/screens/Orders/index.tsx
- src/screens/OutboundStockList/index.tsx
> OBKN-407 Display picking list when there is only 1 item on the list

- src/screens/InboundOrder/index.tsx
[Chore] Update the destination and  item status validations
> OBKN-412 Display on Inbound list only shipments with destination=current location

- src/screens/PickList/index.tsx
Fixed issue of quantity to take more time to increment
> OBKN-441 Improve display of validation errors on picking screen

- .eslintrc.js
- src/Main.tsx
- src/apis/transfers.ts
- src/redux/actions/transfers.ts
- src/redux/reducers/mainReducer.ts
- src/redux/sagas/transfers.ts
- src/screens/Dashboard/dashboardData.ts
- src/screens/Transfers/index.tsx
- src/screens/Transfers/styles.ts
- src/screens/Transfers/types.ts
- src/screens/TransfersDetails/index.tsx
- src/screens/TransfersDetails/styles.tsx
- yarn.lock
Allow a forklift driver to view all pending transfer orders
> OBKN-104/105 Allow a forklift driver to view all pending transfer orders

- src/screens/InboundReceiveDetail/index.tsx
- src/screens/InboundReceiveDetail/styles.ts
https://pihemr.atlassian.net/browse/OBKN-545
> OBKN-545 : Allow user to enter status code on receiving screen when receiving an item

- src/redux/sagas/auth.ts
OBKN-510 Mobile app reports "server unavailable" on authentication errors like incorrect password
> OBKN-510 : Handle user authenticate invalid user name and password

- src/apis/orders.ts
Requires this fix https://github.com/openboxes/openboxes/pull/3160 to be working
> OBKN-602 Sort Order list by expectedShippingDate (ascending)

- src/screens/InboundDetails/InboundOrderContainer.tsx
- src/screens/InboundDetails/styles.ts
OBKN-587: Refactor old items styling into Card
Info: removed the header title border from the inbound details screen
> OBKN-587 Removed the header title border from inbound details screen

- src/data/picklist/PicklistItem.ts
- src/screens/PickList/index.tsx
- src/screens/PickList/styles.ts
Depends on OBKN-607 which can now be merged.
> OBKN-609 Display shortage details on Order Details screen

- src/Main.tsx
- src/apis/orders.ts
- src/data/container/Shipment.ts
- src/data/order/Order.ts
- src/redux/actions/orders.ts
- src/redux/sagas/orders.ts
- src/screens/InternalLocationDetails/index.tsx
- src/screens/OrderDetails/OrderDetailsVm.ts
- src/screens/OrderDetails/index.tsx
- src/screens/PackingLocationPage/index.tsx
- src/screens/PackingLocationPage/styles.ts
1. OBKN-669 Fix scroll on the Available items on InternalLocationDetailscreen.
2. OBKN-611 Allow user to move picked items to the packing location:
- OBKN-611 Allow user to move picked items to the packing location,
- OBKN-611 Add button for moving to packing.
> Merge develop into master
